[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.autopep8]
select = ["E231"]

[tool.coverage.report]
show_missing = true

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--mypy --cov=blackbody"
