from numpy import float64
from numpy.typing import ArrayLike, NDArray

from ._constants import *
from ._planck import *


def spectral_radiant_sterance(T: ArrayLike, x: ArrayLike, *, spectral_unit: str, area_unit: str) -> NDArray[float64]: ...
def spectral_photon_sterance(T: ArrayLike, x: ArrayLike, *, spectral_unit: str, area_unit: str) -> NDArray[float64]: ...
def integrated_radiant_sterance(T: ArrayLike, x_ab: ArrayLike, *, spectral_unit: str, area_unit: str) -> NDArray[float64]: ...
def integrated_photon_sterance(T: ArrayLike, x_ab: ArrayLike, *, spectral_unit: str, area_unit: str) -> NDArray[float64]: ...
