name: docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v7

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version

      - name: Build docs
        run: |
          uv run mkdocs build

      - name: Publish docs
        if: ${{ !env.ACT }}
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site/
          force_orphan: true
